spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-22.railway.app:5432/seubanco
    username: seuusuario
    password: suasenha
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
